config/routes.rb
Rails.application.routes.draw do
  get "skills/index"
  get "contact/index"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: redirect("/personal")
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :about
  resources :personal
  resources :contact
  resources :skills
  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/personal_controller.rb
class PersonalController < ApplicationController
  def index
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/about/index.html.erb
<div id="aboutSection">
    <div id="aboutDom">
        <div>
            <h2 id="aboutTitle">About Me</h2>
            <p class="aboutText">I am a software developer with experience in front-end technologies and currently learning back-end development. 
                My specialty is building web and mobile applications tailored to the client’s needs.</p>
            <p class="aboutText">My approach focuses on maintaining clean and scalable code, following industry best practices.</p>
        </div>
        <div id="aboutImage">
            <%= image_tag "james-harrison-vpOeXr5wmR4-unsplash.jpg", alt: "Representative image" %>
        </div>
    </div>
</div>

app/views/contact/index.html.erb
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<section id="contactSection" class="text-center py-5">
    <h1 id="contact" class="mb-4">Contact</h1>
    <p id="textContact" class="mb-4">Interested in working together? You can reach out to me through the following platforms.</p>

    <div class="icon-container mb-4">
        <a href="https://www.linkedin.com/in/martin-rodriguez-riquelme-231189204/" class="icon-circle me-3">
            <%= image_tag "linkedin-brands.svg", width: 50, height: 50, alt: "LinkedIn" %>
        </a>
        <a href="https://github.com/MartinRodriguez2001" class="icon-circle me-3">
            <%= image_tag "github-brands.svg", width: 50, height: 50, alt: "GitHub" %>
        </a>
        <a href="mailto:marodriguez8@miuandes.cl" class="icon-circle">
            <%= image_tag "envelope-solid.svg", width: 50, height: 50, alt: "Email" %>
        </a>
    </div>
    <div class="container">
        <form id="contactForm" class="mx-auto" style="max-width: 400px;" onsubmit="showThankYouMessage(event)">
            <div class="mb-3">
                <label for="name" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Your Name" required>
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Your Email" required>
            </div>
            <div class="mb-3">
                <label for="message" class="form-label">Message</label>
                <textarea class="form-control" id="message" name="message" rows="4" placeholder="Your Message" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary w-100">Submit</button>
        </form>

        <p id="thankYouMessage" class="mt-4 text-success" style="display: none;">Thank you for your message, we will contact you soon.</p>
    </div>

  
    <script>
        function showThankYouMessage(event) {
            event.preventDefault(); 
            document.getElementById("contactForm").style.display = "none"; 
            document.getElementById("thankYouMessage").style.display = "block"; 
        }
    </script>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Portfolio" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap">
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
     <%= render 'shared/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/personal/index.html.erb
<body>
<div id="hero">
    <div id="imagen">
        <%= image_tag "163907287.jpeg", alt: "Imagen de perfil" %>
    </div>

    <h1 id="mainName">Martín Rodríguez</h1>
    <h2 id="mainDes">Software Developer</h2>
</div>

</body>

app/views/shared/_navbar.html.erb
<div id="navBar">
    <div id="name">
        <%= link_to "Martín Rodriguez", personal_index_path, class: "links" %>
        <p>Martín Rodriguez</p>
    </div>
    <div id="navBarLinks">
        <%= link_to "About Me", about_index_path, class: "links" %>
        <%= link_to "Skills", skills_index_path, class: "links" %>
        <%= link_to "Contact", contact_index_path, class: "links" %>
    </div>  
</div>

app/views/skills/index.html.erb
<section id="interestSection" data-controller="portfolio">
    <h1 id="interestTitle">Skills</h1>
    <div id="interesContainer"></div>
</section>

<script src="scripts.js"></script>